### ISSUE TITLE
projectCollections

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#13]
A first sketch for the Collections. This happens inside projects. Much like a Trello / Kanban / Agile board. It is used to sort technologies across a collection set.

![projectcollections](https://cloud.githubusercontent.com/assets/533339/11792459/5c88fea0-a28d-11e5-92e5-bc5263320b50.png)

## ToDo

- [ ] Actions to create collections
- [X] Models for Collection / Sub-collection
- [X] Model for Collection Type
- [ ] Add a toggle for a compact visualization (only title, status & comments & side/inline thumbnail)
- [ ] Horizontal scroll– Research slimScroll.js

## Features

![screen shot 2015-12-09 at 5 43 29 pm](https://cloud.githubusercontent.com/assets/533339/11696616/659013e8-9e9c-11e5-9d15-a615fa18d3d6.png)

- This shows a compact Technology card view.
- It doesn't show the shortText or Tags.
- "Proposed" is the revision status for that technology inside the collection. 
- Comments are also tied to that collection/technology.

### v0.1

![screen shot 2015-12-09 at 5 35 18 pm](https://cloud.githubusercontent.com/assets/533339/11696422/51ce8098-9e9b-11e5-9d3e-2b04a813e77d.png)

**Comment by arthursoares** [comment]
Updates! :+1:
