### ISSUE TITLE
Recent Updates format

### ISSUE THREAD

**Issue by arthursoares** [envisioning/tdb#144]
## MainDashboard

<img width="699" alt="screen shot 2016-03-22 at 1 18 37 pm" src="https://cloud.githubusercontent.com/assets/533339/13952837/acd30bd0-f030-11e5-8e36-98837adad125.png">

* It has an Icon inside the label with the object's property.
* Only technologies have color-coded status

## Inside Technologies Dashboard  
<img width="1066" alt="screen shot 2016-03-22 at 12 19 09 pm" src="https://cloud.githubusercontent.com/assets/533339/13951348/51d70176-f028-11e5-94dd-97e98e957994.png">

Use this format.

Code is available at https://github.com/envisioning/tdb/blob/eb1146f5630c611032daaa850967f8557aefb46e/technologyDashboard.php#L65

**Comment by lnmunhoz** [comment]
**TODO**:
- [ ] Fix colors

Partial redesign here 6ac8540f28962d9b3382c631b0f629ec68522038

**Comment by rafaelcorreiapoli** [comment]
Arthur, a cor irá refletir o status da tecnologia, certo?
A cor deve ser fixa temporalmente? Exemplo:
Quando eu dei um update na tecnologia, ela estava em draft, portanto a label será desenhada em vermelho. 
Quando eu colocar a tecnologia em Published, essa label deve se tornar verde? Ou deverá permanecer vermelha pois no momento em que aquele log foi criado ela estava em draft?
Resumindo a pergunta: Esta cor deve acompanhar o estado atual da tecnologia ou guardar o estado da tecnologia quando o log foi registrado ?

**Comment by rafaelcorreiapoli** [comment]
- [ ] Make Icon optional
- [ ] Make color optional
- [ ] Pass a function to determine the color

**Comment by arthursoares** [comment]
@rafaelcorreiapoli não tinha visto. Ele acompanha o estado atual.

**Comment by rafaelcorreiapoli** [comment]
Então está feito! Dando merge na staging você já confere e podemos fechar
